FROM cloudfoundry/cflinuxfs2

WORKDIR /work

RUN apt-get update; \
    apt-get install -y wget python-pip python-dev python-numpy swig git zip; \
    apt-get install -y libagg-dev libpotrace-dev;

# environment variabless
ENV GDAL_VERSION=1.11.5 \
    LD_LIBRARY_PATH=/usr/local/lib \
    GDAL_CONFIG=/usr/local/bin/gdal-config

RUN \
    wget http://download.osgeo.org/gdal/$GDAL_VERSION/gdal-$GDAL_VERSION.tar.gz && \
    tar -xzvf gdal-$GDAL_VERSION.tar.gz && \
    cd gdal-$GDAL_VERSION && \
    ./configure \
        --with-python=yes \
        --with-hdf4=no \
        --with-hdf5=no \
        --with-threads \
        --with-gif=no \
        --with-pg=no \
        --with-grass=no \
        --with-libgrass=no \
        --with-cfitsio=no \
        --with-pcraster=no \
        --with-netcdf=no \
        --with-png=no \
        --with-jpeg=no \
        --with-gif=no \
        --with-ogdi=no \
        --with-fme=no \
        --with-jasper=no \
        --with-ecw=no \
        --with-kakadu=no \
        --with-mrsid=no \
        --with-jp2mrsid=no \
        --with-bsb=no \
        --with-grib=no \
        --with-mysql=no \
        --with-ingres=no \
        --with-xerces=no \
        --with-expat=no \
        --with-odbc=no \
        --with-curl=yes \
        --with-sqlite3=no \
        --with-dwgdirect=no \
        --with-idb=no \
        --with-sde=no \
        --with-perl=no \
        --with-php=no \
        --without-mrf \
        --with-hide-internal-symbols=yes \
        CFLAGS="-O2 -Os" CXXFLAGS="-O2 -Os" && \
        make && make install && cd .. && \
        rm -rf gdal-$GDAL_VERSION*

# install requirements
COPY requirements.txt /work/requirements.txt
COPY requirements-dev.txt /work/requirements-dev.txt

RUN \
    pip install wheel cython numpy; \
    pip install -r requirements.txt; \
    pip install -r requirements-dev.txt;
