FROM centos:latest

WORKDIR /work

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/work/lib:/work/lib64:/work/lib64/mysql:/work/lib64/atlas
ENV PYTHONPATH=$PYTHONPATH:/work/lib/python2.7/site-packages:/work/lib64/python2.7/site-packages

